name: ""      # name of the deployment
provider: libvirt

common:                                 # generic infrastructure settings
    qemu_uri: qemu:///system            # qemu uri for the KVM hypervisor
    storage_pool: default               # the pool where the volume images are stored
    private_ip_range: 192.168.10.0/24   # private network range
    public_ip_range: 10.10.10.0/24      # public network range (NAT network)
    public_bridge: ""                   # if set (eg: "br0"), has precedence and allows public access
    shared_storage_type: shared-disk    # fencing mechanism, can be shared-disk or iscsi
    reg_email: ""
    reg_code: ""
    network_domain: local
    username: root
    password: linux

    source_image: ""                    # url for the image of the OS
    volume_name: ""                     # alternatively, in KVM, a volume can be specified
    additional_repos: 
        ha: http://download.opensuse.org/repositories/network:ha-clustering:sap-deployments:devel
    additional_pkgs: []

    cpus: 2                  # number of cpus per node
    memory: 1024             # memory in MiB
    disk_size: 1             # size of the data disk in GB

node:                        # cluster nodes specific options
    count: 2                 # number of cluster nodes
    disk_size: 64            # disk size in GB

iscsi:                       # iscsi server specific options
    device: "/dev/vdb"       # iSCSI device in server
    disks: 0                 # Number of partitions attach to iscsi server. 0 means all

sbd: {}

qdevice:                     # monitor specific config
    enabled: false           # indicates if qdevice is used
    options: ""

examiner:
    enabled: false
