# This locals entry is used to store the IP addresses of all the machines.
# Autogenerated addresses example based in 19.168.135.0/24
# iscsi server: 19.168.135.4
# monitor: 19.168.135.5
# node ips: 19.168.135.10, 19.168.135.11, ...
# If the addresses are provided by the user they will always have preference

locals {
    iscsi_private_ip = var.iscsi_private_ip != "" ? var.iscsi_private_ip : cidrhost(local.ip_range, 4)
  
    monitor_private_ip = var.monitor_private_ip != "" ? var.monitor_private_ip : cidrhost(local.ip_range, 5)

    node_private_ips_start = 10
    node_private_ips       = length(var.node_private_ips) != 0 ? var.node_private_ips : [for ip_index in range(local.node_private_ips_start, local.node_private_ips_start + var.node_count) : cidrhost(local.ip_range, ip_index)]
}

module "node" {
    source                = "./modules/node"
    name                  = "node"
    source_image          = var.node_source_image
    volume_name           = var.node_source_image != "" ? "" : (var.node_volume_name != "" ? var.node_volume_name : local.base_volume_name)
    storage_pool          = var.storage_pool
    node_count            = var.node_count
    cpus                  = var.node_cpus
    memory                = var.node_memory
    disk_size             = var.node_disk_size
    mac                   = ""
    bridge                = "br0"
    nat_network_name      = ""
    isolated_network_id   = local.internal_network_id
    isolated_network_name = local.internal_network_name
    node_private_ips      = local.node_private_ips
    shared_storage_type   = var.shared_storage_type
    sbd_disk_id           = module.sbd_disk.id
}

module "iscsi" {
    source                = "./modules/iscsi"
    source_image          = var.iscsi_source_image
    volume_name           = var.iscsi_source_image != "" ? "" : (var.iscsi_volume_name != "" ? var.iscsi_volume_name : local.base_volume_name)
    storage_pool          = var.storage_pool
    iscsi_enabled         = var.shared_storage_type == "iscsi"
    cpus                  = var.iscsi_cpus
    memory                = var.iscsi_memory
    disk_size             = var.iscsi_disk_size
    iscsi_dev             = "/dev/vdb"
    mac                   = ""
    bridge                = "br0"
    nat_network_name      = ""
    isolated_network_id   = local.internal_network_id
    isolated_network_name = local.internal_network_name
    iscsi_private_ip      = local.iscsi_private_ip
}

module "monitor" {
    source                = "./modules/monitor"
    name                  = "monitor"
    source_image          = var.monitor_source_image
    volume_name           = var.monitor_source_image != "" ? "" : (var.monitor_volume_name != "" ? var.monitor_volume_name : local.base_volume_name)
    storage_pool          = var.storage_pool
    monitor_enabled       = var.monitor_enabled
    cpus                  = var.monitor_cpus
    memory                = var.monitor_memory
    mac                   = ""
    bridge                = "br0"
    nat_network_name      = ""
    isolated_network_id   = local.internal_network_id
    isolated_network_name = local.internal_network_name
    monitor_private_ip    = local.monitor_private_ip
}
